name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Deploy index.html to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa app/index.html ec2-user@${{ secrets.EC2_HOST }}:/tmp/index.html
      - name: Move file and restart nginx
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_HOST }} '
            sudo mv /tmp/index.html /usr/share/nginx/html/index.html &&
            sudo systemctl restart nginx
            '
